config/routes.rb
Exam::Application.routes.draw do

  root :to=>"home#index"
  	
  resources :sessions
  get "sessions/new"
  get "login" => "sessions#new", :as => "login"
  match "logout" => "sessions#destroy"
  match "update" => "sessions#update"
  
  
  
  resources :ankets
  match "anket" => "ankets#index" ,:as => "anket"
  match "ankets/:id" => "ankets#show" ,:as => "show"
  match "show_sec" => "ankets#show_sec" 
  match "admin" => "ankets#admin" ,:as => "admin"
  match "finish" => "ankets#finish" ,:as => "finish"
  match "finish_sec" => "ankets#finish_sec" ,:as => "finish_sec"
  match "dagitim" => "ankets#dagitim" ,:as => "dagitim"
  match "kimlik" => "ankets#kimlik" ,:as => "kimlik"
  
  resources :passwords
  match "password" => "passwords#new" 
  
  
 
end

app/models/anket.rb
class Anket < ActiveRecord::Base
  attr_accessible :answer,:name,:userid, :time,:anketid
  belongs_to :user
  belongs_to :identity
end

app/models/classname.rb
class Classname < ActiveRecord::Base
  attr_accessible :classname, :desk, :examdate, :floor, :schoolname, :totaldesk
  belongs_to :identity
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  attr_accessible :clsname, :exmdate, :exmdesk, :flat, :name, :no, :schname, :ttldesk
  belongs_to :classname
  validates :exmdesk, :presence => true
  validates :exmdesk, :uniqueness => true
end

app/models/password.rb
class Password < ActiveRecord::Base
  attr_accessible :new_password, :new_password_confirmation, :userid
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
 
  attr_accessible :username, :password ,:password_confirmation, :role, :userlogin, :okulno
  has_secure_password
  
  
  ROLES = %w[student admin]

  def role?(base_role)
      ROLES.index(base_role.to_s) <= ROLES.index(role)
  end
  
  
end

app/controllers/ankets_controller.rb
class AnketsController < ApplicationController

  @@time_finish = Time.zone.parse("2013-01-21 14:09 ") #anket süresi
  @@exam_date = Time.zone.parse("2013-02-16 12:00 ") #sınav tarihi
  
  def index
	@ankets = Anket.all
	@student = User.find(session[:user_id])
	@find = Anket.find_by_userid(@student.id)
	
	if @student.userlogin >= @@time_finish
		if @find == nil
			redirect_to ("/finish_sec")
		else
			if @find.answer == "EVET"
				redirect_to ("/kimlik")
			else
				redirect_to ("/finish_sec")
			end
		end
	end
	
  end
  
  def show
	@anket = Anket.new
	@anket.id = params[:id]
	@student = User.find(session[:user_id])
	@anket.name = @student.username
	
	if @anket.id == 1
		@anket.answer = "EVET"
	end
	
	if @anket.id == 2 
		@anket.answer = "HAYIR"
	end
	
	@find = Anket.find_by_userid(@student.id)
	
	
	if @find == nil
	
		Anket.create(
			userid: @student.id, 
			answer: @anket.answer, 
			name: @student.username,
			time: Time.now
		)
		
	else
	    @find.update_attribute(:time, Time.now)
		if @student.userlogin >= @@time_finish or Time.now >= @@time_finish
			if @find.answer == "EVET"
				redirect_to ("/show_sec")
			else
				redirect_to ("/finish_sec")
			end
		else
			@find.update_attribute(:answer, @anket.answer)
			@find.update_attribute(:time, Time.now)
		end
	end
  end
  
  def finish
	@student = User.find(session[:user_id])
	@find = Anket.find_by_userid(@student.id)
	
  end
  
  def show_sec
	@student = User.find(session[:user_id])
	@find = Anket.find_by_userid(session[:user_id])
	@find.update_attribute(:time, Time.now)
	if @student.userlogin >= @@time_finish or Time.now >= @@time_finish
		if @find.answer == "EVET"
			redirect_to ("/kimlik")
		else
			redirect_to ("/finish_sec")
		end
	end
	
  end
  
  
  def admin 
	@anket = Anket.all
	@time_finish = @@time_finish
	
  end
  
  
  def dagitim
	@anket = Anket.all
	@kimlik = Identity.all
	@anket.each do |anket|
		@class = Classname.all.shuffle[0..0]
		@student2 = User.find_by_username(anket.name)
		@find2 = Identity.find_by_name(anket.name)
		if @find2 == nil and anket.answer == "EVET"
			@class.each do |idc|
				Identity.create(
					name: anket.name,
					no: @student2.okulno,
					schname: idc.schoolname,
					clsname: idc.classname,
					flat: idc.floor,
					exmdate: idc.examdate,
					exmdesk: idc.desk,
					ttldesk: idc.totaldesk
			    )
			 
			end
		end
	 end
  end
  
  def kimlik
	@student = User.find(session[:user_id])
	@kart = Identity.find_by_name(@student.username)
	unless @kart != nil
		redirect_to("/finish")
	end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "yeterli yetkiniz yok."
    redirect_to root_url
  end
  def current_user
      session[:user_id] ? @current_user ||= User.find(session[:user_id]) : nil
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	
  end
  
  def set_locale
      I18n.locale = session[:lang] || I18n.default_locale
      { :locale => session[:lang] }
  end

  def lang
      session[:lang] = params[:locale]
      redirect_to request.env['HTTP_REFERER']
  end

end

app/controllers/passwords_controller.rb
# encoding: utf-8
class PasswordsController < ApplicationController
  
  def new
    @password = Password.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @password }
    end
  end

  def create
    @password = Password.new(params[:password])
    @user = User.find_by_id(session[:user_id])
    @password_id = Password.find_by_userid(session[:user_id])
    
    respond_to do |format|
      if @password_id == nil 
		Password.create( 
		
			userid: @user.id,
			new_password: @password.new_password,
			new_password_confirmation: @password.new_password_confirmation
		)
		if @password.new_password == @password.new_password_confirmation
			@user.update_attribute(:password, @password.new_password)
			format.html { redirect_to ("/anket"), notice: 'Password was successfully created.' }
			format.json { render json: ("/anket"), status: :created, location: @password }
		else
			format.html { render action: "new" }
			format.json { render json: @password.errors, status: :unprocessable_entity }
			flash[:error] = "Parola Eşleşmesinde Hata Var!"
		end
		
	  else
		if @password.new_password == @password.new_password_confirmation
			@user.update_attribute(:password, @password.new_password)
			format.html { redirect_to ("/anket"), notice: 'Password was successfully created.' }
			format.json { render json: ("/anket"), status: :created, location: @password }
		else
			format.html { render action: "new" }
			format.json { render json: @password.errors, status: :unprocessable_entity }
			flash[:error] = "Parola Eşleşmesinde Hata Var!"
		end
	  end
    end
  end


  def destroy
    @password = Password.find(params[:id])
    @password.destroy

    respond_to do |format|
      format.html { redirect_to passwords_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
 
 def new
    redirect_to deneme_index_path if session[:user_id]
 end

 def create
    user = User.find_by_username(params[:username])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        @password_id = Password.find_by_userid(session[:user_id])
        @find = Anket.find_by_userid(session[:user_id])
        user.update_attribute(:userlogin, Time.now)
        if user.role == "student" && @password_id == nil
			redirect_to ("/password")
		end
		if user.role == "student" && @password_id != nil
			unless @find == nil 
				redirect_to ("/show_sec")
			else
				redirect_to ("/anket")
			end
		end
	
        if user.role == "admin"
            redirect_to ("/admin")
        end
         
    else
        flash[:error] = "Kullanici adin ve/veya parolan hatali"
        redirect_to root_url
    end
 end
 
 def destroy
 
    session[:user_id] = nil
    redirect_to root_url
 
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
        session[:user_id] ? @current_user ||= User.find(session[:user_id]) : nil 
    end
end

app/views/ankets/admin.html.slim
javascript:
 | function gizli(){
         | jQuery("div.gizli").toggle(100);
	 | }

  | function show(){
         | jQuery("div.gizli").hide(100);
	 | }
.hero-unit style="background-color:#ffffff;"
  h3 ANKET CEVAP TABLOSU
  table.table.table-striped.display
	 thead
	   tr
		 th NO
		 th Username
		 th Answer
		 th Created at
		 th Updated at
	 tbody
	   - @anket.each do |anket|
		 tr
		   td= anket.userid
		   td= anket.name
		   td= anket.answer
		   td= anket.created_at
		   td= anket.updated_at
			
	 = button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger', \
		style: "width:220px;position:absolute;top:5in;left:3in;"
	
	 - if Time.now < @time_finish
		= button_to "SINIFLARA DAĞIT", "/dagitim", :class => 'btn btn-large btn-warning', \
				style: "width:220px;position:absolute;top:5in;left:8in;", :disabled => true
	 - else
		= button_to "SINIFLARA DAĞIT", "/dagitim", :class => 'btn btn-large btn-info', \
				style: "width:220px;position:absolute;top:5in;left:8in;"
				
	
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/ankets/dagitim.html.slim
.hero-unit style="background-color:#ffffff;"
  
	h3 SINIFLARA DAĞILIM TABLOSU
	table.table.table-striped.display
	  thead
		tr
		  th Numara
		  th Kullanıcı İsim
		  th Sınav Yeri
		  th Sınıf
		  th Sıra No
		  th Sınav Tarihi
		  
	  tbody
		- @kimlik.each do |kimlik|
		  tr
			td= kimlik.no
			td= kimlik.name
			td= kimlik.schname
			td= kimlik.clsname
			td= kimlik.exmdesk
			td= kimlik.exmdate
			
	= button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger', \
		style: "width:220px;position:relative;top:0.5in;left:4.7in;"
		
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013
            

app/views/ankets/finish.html.slim
.container
  .hero-unit style="position:absolute;top:100px;left:300px;width:6in;"
    h2 style="color:#990033" 
		|Sınava Girme İsteğiniz 
		span style="color:green;font-weight:bold;" EVET  
		|  Olarak Kaydedilmiştir.
		|  Sınav Giriş Kartınız En Kısa Zaman İçinde Verilecektir.
    
  = button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger',\
	style: "width:120px;position:relative;top:390px;left:3.5in;width:2in;"
	
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/ankets/finish_sec.html.slim
.container
  .hero-unit style="position:absolute;top:100px;left:330px;width:6in;"
    h2 style="color:#990033" 
    
		| Anket süremiz dolmuştur.  İlginiz için teşekkür ederiz.

  = button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger',\
	style: "width:120px;position:relative;top:370px;left:4in;width:2in;"
	
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013	

app/views/ankets/index.html.slim
.container
  .hero-unit style="position:absolute;top:120px;left:290px;"
    h2 style="color:#990033" Muafiyet Sınavına Girmek İster misiniz? 
    
  .row
    .span10.offset3
      div style="position:absolute;top:280px"
        = button_to "EVET", { :action => "show", :id => 1, :method => :get }, :class => 'btn btn-large btn-info',\
			style: "width:120px;position:relative;left:-20px;top:50px;"
        = button_to "HAYIR", { :action => "show", :id => 2,  :method => :get }, :class => 'btn btn-large btn-danger', \
			style: "width:120px;position:relative;left:330px;top:-10px;"
			
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/ankets/kimlik.html.slim
.container
  .hero-unit style="position:absolute;top:20px;left:280px;width:6in;background-color:white;"
    h3 style="color:#990033"  SINAV GİRİŞ KARTI
	table.table.table-bordered.display
      thead
        tr
          th ÖĞRENCİ NUMARASI
          td= @kart.no
        tr
          th İSİM-SOYİSİM
          td= @kart.name
        tr
          th SINAV YERİ
          td= @kart.schname
        tr
          th SINAV SALON NO
          td= @kart.flat
        tr
          th SINAV SINIFI
          td= @kart.clsname
        tr
          th SIRA NO
          td= @kart.exmdesk
        tr
          th SINAV TARİHİ
          td= @kart.exmdate
          	
    = button_to "İNDİR", "#", :class => 'btn btn-large btn-primary', \
		style: "width:220px;position:absolute;top:4.5in;left:2.3in;"
            
    
 
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/ankets/show.html.slim
.container
  .hero-unit style="position:absolute;top:100px;left:330px;width:6in;"
    h2 style="color:#990033"
      | Cevabınız   
      span style="color:green;font-weight:bold;"  =  @anket.answer   
      |   Olarak Kaydedilmiştir. Son Değiştirme Tarihiniz : 
      - @time_finish = Time.zone.parse("2012-12-09 22:34 ")
	  span  style="color:green;font-weight:bold;" = @time_finish.strftime ( "%d %B %Y  %H:%M")
  .row style="position:absolute;top:280px;left:600px;"
    = button_to "DEĞİŞTİR", anket_path, :class => 'btn btn-large btn-info', \
		style: "width:120px;position:relative;top:120px;left:-1.5in;"
		
    = button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger', \
		style: "width:120px;position:relative;top:60px;left:1.5in;"
		
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/ankets/show_sec.html.slim
.container
  .hero-unit style="position:absolute;top:100px;left:330px;width:6in;"
    h2 style="color:#990033"
      | Cevabınız  
      span style="color:green;font-weight:bold;" = @find.answer   
      |   Olarak Kaydedilmiştir. Son Değiştirme Tarihiniz : 
      - @time_finish = Time.zone.parse("2012-12-09 22:34 ")
	  span  style="color:green;font-weight:bold;" = @time_finish.strftime ( "%d %B %Y  %H:%M")
  .row style="position:absolute;top:280px;left:600px;"
    = button_to "DEĞİŞTİR", anket_path, :class => 'btn btn-large btn-info', \
		style: "width:120px;position:relative;top:140px;left:-1.5in;"
		
    = button_to "ÇIKIŞ", logout_url, :class => 'btn btn-large btn-danger', \
		style: "width:120px;position:relative;top:80px;left:1.5in;"
		
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/home/index.html.slim
.container
  .hero-unit style="position:absolute;top:120px;left:180px;"
    h2 style="color:black" Muafiyet Sınavı
    p
      a.btn.btn-primary.btn-large style="position:relative;top:30px;left:30px;"   Daha fazla bilgi &raquo;
     
.row
  .span8.offset2
    div style="position:absolute;top:130px;left:8in"
      = form_tag sessions_path,:class=>"form-horizontal" do
        legend= "Kullanıcı Girişi"
        - if flash[:error]
          .alert.alert-error
            = flash[:error]
        .control-group
          label.control-label= "Kullanıcı Adı"
          = text_field_tag :username, params[:username], :style => "height:30px;"
        div class="control-group>"
          label.control-label= "Parola"
        
          = password_field_tag :password , nil ,  :style => "height:30px;"
        = submit_tag "Giriş Yap", :class => "btn btn-primary", :style => "position:relative;top:30px;left:-150px;"
.well.navbar-fixed-bottom
  .container
    .row
      .span4.offset4
        span.copyright Copyright © BETÜL SARAL 2013

app/views/layouts/application.html.slim
doctype
html
  head
    title Muafiyet
	= stylesheet_link_tag 'bootstrap', media: 'all' 
	= stylesheet_link_tag 'bootstrap.min', media: 'all' 
	= stylesheet_link_tag 'anket', media: 'all' 
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="/" style="color:#C9C299" Muafiyet Sınavı
          .nav-collapse
            ul.nav
              li.active
                a href="/" Ana Sayfa
            ul.nav.pull-right
              - if current_user
                li= link_to current_user.username,""
                li
                  = link_to "Çıkış",logout_url
              li
                - if flash[:error]
                  .alert.alert-error
                    = flash[:error]
              ul
        /! /.nav-collapse
    = yield